rr_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: first_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: second_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}