rr_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

 
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - first_joint
      - second_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      first_joint: {trajectory: 10.0, goal: 10.0}
      second_joint: {trajectory: 10.0, goal: 10.0}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
