youbot_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1