sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 12
    max_update_rate: 1.0
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /scan
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater