// Generated by gencpp from file slam_toolbox_msgs/Reset.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_RESET_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <slam_toolbox_msgs/ResetRequest.h>
#include <slam_toolbox_msgs/ResetResponse.h>


namespace slam_toolbox_msgs
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace slam_toolbox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_toolbox_msgs::Reset > {
  static const char* value()
  {
    return "d183d6d1f6b03b1483ab508f22fac253";
  }

  static const char* value(const ::slam_toolbox_msgs::Reset&) { return value(); }
};

template<>
struct DataType< ::slam_toolbox_msgs::Reset > {
  static const char* value()
  {
    return "slam_toolbox_msgs/Reset";
  }

  static const char* value(const ::slam_toolbox_msgs::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::slam_toolbox_msgs::ResetRequest> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::Reset >
template<>
struct MD5Sum< ::slam_toolbox_msgs::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::Reset >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::ResetRequest> should match
// service_traits::DataType< ::slam_toolbox_msgs::Reset >
template<>
struct DataType< ::slam_toolbox_msgs::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::Reset >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_toolbox_msgs::ResetResponse> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::Reset >
template<>
struct MD5Sum< ::slam_toolbox_msgs::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::Reset >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::ResetResponse> should match
// service_traits::DataType< ::slam_toolbox_msgs::Reset >
template<>
struct DataType< ::slam_toolbox_msgs::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::Reset >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_RESET_H
