// Generated by gencpp from file slam_toolbox_msgs/ResetRequest.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_RESETREQUEST_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_RESETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slam_toolbox_msgs
{
template <class ContainerAllocator>
struct ResetRequest_
{
  typedef ResetRequest_<ContainerAllocator> Type;

  ResetRequest_()
    : pause_new_measurements(false)  {
    }
  ResetRequest_(const ContainerAllocator& _alloc)
    : pause_new_measurements(false)  {
  (void)_alloc;
    }



   typedef uint8_t _pause_new_measurements_type;
  _pause_new_measurements_type pause_new_measurements;





  typedef boost::shared_ptr< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetRequest_

typedef ::slam_toolbox_msgs::ResetRequest_<std::allocator<void> > ResetRequest;

typedef boost::shared_ptr< ::slam_toolbox_msgs::ResetRequest > ResetRequestPtr;
typedef boost::shared_ptr< ::slam_toolbox_msgs::ResetRequest const> ResetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator1> & lhs, const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pause_new_measurements == rhs.pause_new_measurements;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator1> & lhs, const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_toolbox_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8fd9baf49824dc9215dabe1b6b58b4a";
  }

  static const char* value(const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8fd9baf49824dc9ULL;
  static const uint64_t static_value2 = 0x215dabe1b6b58b4aULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_toolbox_msgs/ResetRequest";
  }

  static const char* value(const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Set this to 'true' to pause new measurements immediately after reset.\n"
"# Note: This is a set behaviour and not a toggle behaviour, contrary to Pause.srv service.\n"
"bool pause_new_measurements\n"
;
  }

  static const char* value(const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pause_new_measurements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_toolbox_msgs::ResetRequest_<ContainerAllocator>& v)
  {
    s << indent << "pause_new_measurements: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pause_new_measurements);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_RESETREQUEST_H
